CREATE TABLE `visit` (
	`id` INT NOT NULL AUTO_INCREMENT ,
	`ip` VARCHAR(50) NOT NULL ,
	`time` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	`source` VARCHAR(255) NULL , PRIMARY KEY (`id`)
) ENGINE = InnoDB; 